language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t csyouk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true csyouk/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-013313634723"
  buckey_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"