language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t csyouk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true csyouk/docker-react npm run test -- --coverage